# Generated by Django 4.2.7 on 2024-05-25 17:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.TextField(verbose_name='корзина'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='-', max_length=20, verbose_name='номер заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='row',
            field=models.IntegerField(verbose_name='ряд'),
        ),
        migrations.AlterField(
            model_name='order',
            name='seat',
            field=models.IntegerField(verbose_name='место'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sector',
            field=models.CharField(max_length=100, verbose_name='сектор'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'Новая'), ('Paid', 'Оплачено'), ('Closed', 'Закрыта')], default='New', max_length=20, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='общая сумма'),
        ),
        migrations.AlterField(
            model_name='order',
            name='userid',
            field=models.CharField(default='-', max_length=30, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=255, verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='количество'),
        ),
        migrations.DeleteModel(
            name='Courier',
        ),
    ]
