# Generated by Django 4.2.7 on 2024-07-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapp', '0002_alter_order_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='row',
            field=models.CharField(max_length=10, verbose_name='ряд'),
        ),
    ]
