# Generated by Django 5.0 on 2024-03-18 05:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vapp", "0002_remove_order_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
