# Generated by Django 5.0 on 2024-03-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vapp", "0003_alter_order_total_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chat_id", models.BigIntegerField(unique=True)),
            ],
        ),
    ]
