# Generated by Django 5.0 on 2024-03-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vapp", "0004_chat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="chat_id",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
