# Generated by Django 5.0 on 2024-03-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vapp", "0005_alter_chat_chat_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="BotUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=255, unique=True)),
                ("first_name", models.CharField(blank=True, max_length=255, null=True)),
                ("last_name", models.CharField(blank=True, max_length=255, null=True)),
                ("username", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
