# Generated by Django 5.0 on 2024-03-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vapp", "0006_botuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="first_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="chat",
            name="username",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
