# Generated by Django 4.2.7 on 2024-03-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapp', '0007_chat_first_name_chat_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='SiteStatistics',
        ),
        migrations.AddField(
            model_name='product',
            name='initial_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
